Added program-launcher example application

diff --git a/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-train b/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-train
--- a/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-train
+++ b/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-train
@@ -1,6 +1,50 @@
 #!/usr/bin/env bash
-install_dir='/usr/lib/rhasspy/train'
-export PATH="${install_dir}:${PATH}"
-export LD_LIBRARY_PATH="${install_dir}:${LD_LIBRARY_PATH}"
 
-"${install_dir}/train" "$@"
+if [[ -z "${rhasspy_dir}" ]]; then
+    export rhasspy_dir='/usr/lib/rhasspy'
+fi
+
+# -----------------------------------------------------------------------------
+# Command-line Arguments
+# -----------------------------------------------------------------------------
+
+. "${rhasspy_dir}/etc/shflags"
+
+DEFINE_string 'profile' '' 'Path to profile directory' 'p'
+
+# training
+DEFINE_boolean 'debug' false 'Print DEBUG messages to console'
+
+FLAGS "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+# -----------------------------------------------------------------------------
+# Default Settings
+# -----------------------------------------------------------------------------
+
+set -e
+
+profile_dir="${FLAGS_profile}"
+
+if [[ "${FLAGS_debug}" -eq "${FLAGS_TRUE}" ]]; then
+    debug='--debug'
+fi
+
+# -----------------------------------------------------------------------------
+# Profile
+# -----------------------------------------------------------------------------
+
+if [[ -z "${profile_dir}" ]]; then
+    echo "Profile is required"
+    exit 1
+fi
+
+# -----------------------------------------------------------------------------
+
+train_dir="${rhasspy_dir}/train"
+
+export PATH="${train_dir}:${PATH}"
+export LD_LIBRARY_PATH="${train_dir}:${LD_LIBRARY_PATH}"
+export profile_dir="$(realpath "${profile_dir}")"
+
+"${train_dir}/train" "$@"
diff --git a/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-vocab_g2p b/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-vocab_g2p
--- a/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-vocab_g2p
+++ b/debian/training/rhasspy-train_1.0_amd64/usr/bin/rhasspy-vocab_g2p
@@ -1,20 +1,88 @@
 #!/usr/bin/env bash
+
+if [[ -z "${rhasspy_dir}" ]]; then
+    export rhasspy_dir='/usr/lib/rhasspy'
+fi
+
+# -----------------------------------------------------------------------------
+# Command-line Arguments
+# -----------------------------------------------------------------------------
+
+. "${rhasspy_dir}/etc/shflags"
+
+# phonetisaurus
+DEFINE_boolean 'debug' false 'Print DEBUG messages to console'
+DEFINE_string 'model' '' 'Path to G2P fst model'
+DEFINE_integer 'nbest' 5 'Maximum number of hypotheses to produce'
+DEFINE_string 'unknown' '' 'Path to unknown words list'
+
+# vocab_g2p
+DEFINE_string 'output' '' 'Path to write guesses'
+
+FLAGS "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+# -----------------------------------------------------------------------------
+# Default Settings
+# -----------------------------------------------------------------------------
+
 set -e
 
-temp_list="$(mktemp)"
-function finish {
-    rm -f "${temp_list}"
-}
+if [[ "${FLAGS_debug}" -eq "${FLAGS_TRUE}" ]]; then
+    debug='true'
+fi
 
-trap finish EXIT
+model="${FLAGS_model}"
+nbest="${FLAGS_nbest}"
+unknown="${FLAGS_unknown}"
+output="${FLAGS_output}"
+
+# -----------------------------------------------------------------------------
+# Required Settings
+# -----------------------------------------------------------------------------
+
+if [[ -z "${model}" ]]; then
+    echo "Model is required"
+    exit 1
+fi
+
+phonetisaurus_args=('--model' "${model}")
+vocab_g2p_args=()
+
+if [[ ! -z "${nbest}" ]]; then
+    phonetisaurus_args+=('--nbest' "${nbest}")
+fi
+
+if [[ ! -z "${debug}" ]]; then
+    vocab_g2p_args+=('--debug')
+fi
+
+if [[ ! -z "${output}" ]]; then
+    vocab_g2p_args+=('--output' "${output}")
+fi
 
 # -----------------------------------------------------------------------------
 
-install_dir='/usr/lib/rhasspy/train'
-export PATH="${install_dir}:${PATH}"
-export LD_LIBRARY_PATH="${install_dir}:${LD_LIBRARY_PATH}"
+if [[ -z "${unknown}" ]]; then
+    # Use temporary file and stdin
+    unknown="$(mktemp)"
+    function finish {
+        rm -f "${unknown}"
+    }
 
-cat > "${temp_list}"
-"${install_dir}/phonetisaurus-apply" \
-    --word_list "${temp_list}" "$@" | \
-    "${install_dir}/vocab_g2p"
+    trap finish EXIT
+
+    cat > "${unknown}"
+fi
+
+phonetisaurus_args+=('--word_list' "${unknown}")
+
+# -----------------------------------------------------------------------------
+
+train_dir="${rhasspy_dir}/train"
+
+export PATH="${train_dir}:${PATH}"
+export LD_LIBRARY_PATH="${train_dir}:${LD_LIBRARY_PATH}"
+
+phonetisaurus-apply "${phonetisaurus_args[@]}" | \
+    "${train_dir}/vocab_g2p" "${vocab_g2p_args[@]}"
diff --git a/training/bin/rhasspy-train-mqtt b/training/bin/rhasspy-train-mqtt
--- a/training/bin/rhasspy-train-mqtt
+++ b/training/bin/rhasspy-train-mqtt
@@ -19,10 +19,8 @@ DEFINE_string 'mqtt-host' '127.0.0.1' 'MQTT server address'
 DEFINE_integer 'mqtt-port' 1883 'MQTT server port'
 DEFINE_string 'mqtt-topic' 'rhasspy/training/#' 'MQTT topic to subscribe to'
 
-# Events
-DEFINE_string 'start-training' 'rhasspy/training/start-training' 'Topic for re-training request'
-DEFINE_string 'training-failed' 'rhasspy/training/training-failed' 'Topic for training failure response'
-DEFINE_string 'training-complete' 'rhasspy/training/training-complete' 'Topic for training completion response'
+# Training
+DEFINE_boolean 'fail-unknown' 'Training fails if there are unknown words'
 
 FLAGS "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
@@ -43,6 +41,10 @@ if [[ "${FLAGS_debug}" -eq "${FLAGS_TRUE}" ]]; then
     debug='--debug'
 fi
 
+if [[ "${FLAGS_fail_unknown}" -eq "${FLAGS_TRUE}" ]]; then
+    fail_unknown='true'
+fi
+
 # -----------------------------------------------------------------------------
 # Profile
 # -----------------------------------------------------------------------------
@@ -57,6 +59,7 @@ source <(rhasspy-yq "${profile_dir}/profile.yml" \
                     -q mqtt_host 'mqtt.host' "${mqtt_host}" \
                     -q mqtt_port 'mqtt.port' "${mqtt_port}" \
                     -q mqtt_topic 'mqtt.topic' "${mqtt_topic}" \
+                    -q custom_words 'training.custom-words-file' "${profile_dir}/custom_words.txt" \
                     -q unknown 'training.unknown-words-file' "${profile_dir}/unknown.txt" \
                     -q guess 'training.guess-words-file' "${profile_dir}/guess_words.json" | \
              tee /dev/stderr)
@@ -102,7 +105,7 @@ function send_event {
 set +e
 
 # Main loop
-mosquitto_sub -v -t "${mqtt_topic}" | \
+rhasspy-jsonl-sub -v -t "${mqtt_topic}" | \
     while read -r topic payload;
     do
         # Split topic by /
@@ -142,13 +145,31 @@ mosquitto_sub -v -t "${mqtt_topic}" | \
                     echo ''
 
                     if [[ -f "${guess}" ]]; then
-                        # Report guessed pronunciations
-                        jq -jcn \
-                           --argjson guess "$(cat "${guess}")" \
-                           '{ "error": "unknown words", "unknown_words":$guess }' | \
-                            send_event "${event_error}${request_id}" '-'
+                        if [[ -z "${fail_unknown}" ]]; then
+                            # Report guessed pronunciations
+                            jq -jcn \
+                               --argjson guess "$(cat "${guess}")" \
+                               '{ "error": "unknown words", "unknown_words":$guess }' | \
+                                send_event "${event_error}${request_id}" '-'
+                        else
+                            # Use first guess and re-train
+                            touch "${custom_words}"
+                            jq -r 'keys[]' < "${guess}" | \
+                                while read -r word;
+                                do
+                                    first_guess="$(jq -r --arg w "${word}" '.[$w][0]' < "${guess}")"
+                                    echo "${word}" "${first_guess}" >> "${custom_words}"
+                                done
+
+                            # Re-train with new words
+                            (rhasspy-train \
+                                 --profile "${profile_dir}" \
+                                 2>&1 | \
+                                 tee /dev/stderr \
+                                     > "${error_file}") || exit 1
+                        fi
                     else
-                        # Simply report unknown words
+                        # No guesses. Simply report that there were unknown words.
                         error_message='unknown words'
                         exit 1
                     fi
